### ISSUE TITLE
linux build crashes when connecting to test.mosquitto.org

### ISSUE THREAD

**Issue by gaillarddamien** [Ambre-io/sparkplugui#1]
./SparkpluGUI-Linux v1.0.0

MQTT host: `test.mosquitto.org`
port: 1883
subscribe to: `spBv1.0/#`

click 'connect', and the app crashes with the following error message:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7743ee]

goroutine 11 [running]:
sparkplugui/backend/sparkplug.(*Payload).DecodePayload(0xc00008ff10, {0xc0001fe000, 0xda, 0xda})
        /home/guillaumeklimek/Projects/sparkplugui/backend/sparkplug/weekaung.go:122 +0x20e
sparkplugui/backend/core.(*App).decode(0x0?, {0xc0001fe000, 0xda, 0x0?})
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/app.go:49 +0x49
sparkplugui/backend/core.(*App).CmdConnect.func1.1()
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/commands.go:73 +0x46
created by sparkplugui/backend/core.(*App).CmdConnect.func1 in goroutine 47
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/commands.go:72 +0x90
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7743ee]

goroutine 8 [running]:
sparkplugui/backend/sparkplug.(*Payload).DecodePayload(0xc00008df10, {0xc000132190, 0x4a, 0x4a})
        /home/guillaumeklimek/Projects/sparkplugui/backend/sparkplug/weekaung.go:122 +0x20e
sparkplugui/backend/core.(*App).decode(0x0?, {0xc000132190, 0x4a, 0x0?})
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/app.go:49 +0x49
sparkplugui/backend/core.(*App).CmdConnect.func1.1()
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/commands.go:73 +0x46
created by sparkplugui/backend/core.(*App).CmdConnect.func1 in goroutine 47
        /home/guillaumeklimek/Projects/sparkplugui/backend/core/commands.go:72 +0x90

```

**Comment by guiklimek** [comment]
Oopsie doopsie 😅

I tried to test and investigate and I'm still not sure to understand..

## Context

There is no tahu support for a Golang implementation of the sparkplug-payload nor a sparkplug-client.

I have found this as a code base: https://github.com/weekaung/sparkplugb-client.

## Core

DecodePayload is directly involved in this error and the code use it like that: https://github.com/Ambre-io/sparkplugui/blob/main/backend/sparkplug/weekaung.go#L104.

I copied the code base and add method from the fresh compiled proto file: https://github.com/Ambre-io/sparkplugui/blob/main/backend/sparkplug/sproto/sparkplug_b.pb.go.

## Understanding

He cannot or doesn't know how to decode an incoming message. I don't yet have the type(s) of messages that are causing the problem here, because some work well, fortunately.

**Comment by guiklimek** [comment]
Oopsie doopsie 😅

## Context

There is no tahu support for a Golang implementation of the sparkplug-payload nor the sparkplug-client.

I have found this as a code base: https://github.com/weekaung/sparkplugb-client.

## Core

DecodePayload is directly involved in this error and the code use it like that: https://github.com/Ambre-io/sparkplugui/blob/main/backend/sparkplug/weekaung.go#L104.

I copied the code base and add method from the fresh compiled proto file: https://github.com/Ambre-io/sparkplugui/blob/main/backend/sparkplug/sproto/sparkplug_b.pb.go.

## Understanding

It cannot or doesn't know how to decode an incoming message. 

I don't yet have the type(s) of messages that are causing the problem here, because some work well, fortunately.

I'm still not sure to understand well what is happening here..

**Comment by marchino2000** [comment]
Windows version crashes as well.

**Comment by guiklimek** [comment]
Hello @marchino2000, thank you for reporting this and sorry for the bad user experience with SparkpluGUI. Do you have more information to give like the context of usage?

I think there are two main problems:
- back: the incomplete Go Sparkplug Client ([fail on decoding](https://github.com/Ambre-io/sparkplugui/issues/1#issue-2118173485)) 
- front: the not optimized tree building that displays topics + Redux Toolkit as Event Handler trick to benchmark

For now, SparkpluGUI can't handle top-level topics that involve a large flow of messages.

Unfortunately, I currently can't do more for this. The cool thing is that with wes-johnson, the main maintainer of the tahu library, [we discussed](https://github.com/eclipse/tahu/issues/352) adding it to the Tahu Project. I will find a moment to make it true, SparkpluGUI gonna have better chance like that.

Also, if you want to contribute, feel free to create a PR!

Peace 🫰

**Comment by marchino2000** [comment]
Hi @guiklimek , thank you for your reply. I find this gui a valuable utility to monitor sparkplug messages, so keep up with the good work! In my case it seems that crash is related to authentication fields: if you leave user and password empty, then you'll get the problem.

**Comment by guiklimek** [comment]
I've fixed the tool's crash and latency issues, in particular those reported by @[gaillarddamien](https://github.com/gaillarddamien) and @[marchino2000](https://github.com/marchino2000).

There were some backend and frontend optimization issues, which I solved using a circular queue of 2000 messages and more flexible components. I also took the opportunity to add a selector for the refresh rate.

Regarding testing, I was using `test.mosquitto.org:1883`, but oddly enough it looks like the brokers hosted by mosquitto haven't been reachable for a few days. I've improved the simulator to make it closer to the public mosquitto broker and to allow stress testing of the tool: https://github.com/Ambre-io/sparkplugui/tree/main/simulator.

The release is available here: https://github.com/Ambre-io/sparkplugui/releases/tag/v1.1.1.

As for the connection issue reported by @[marchino2000](https://github.com/marchino2000), I'll look into it along with the second issue https://github.com/Ambre-io/sparkplugui/issues/2.

Peace ✌️
